apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forex-events-kafka-oauth.fullname" . }}-config
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.springProfile }}"
  SPRING_DATASOURCE_URL: "{{ .Values.env.datasourceUrl }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.env.datasourceUser }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.env.datasourcePassword }}"
  OTEL_SERVICE_NAME: "{{ .Values.env.otelServiceName }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.env.otelEndpoint }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.env.kafkaBrokers }}"
