apiVersion: v1
kind: Service
metadata:
  name: {{ include "forex-events-kafka-oauth.fullname" . }}-svc
  labels:
    app: {{ include "forex-events-kafka-oauth.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "forex-events-kafka-oauth.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
